import { type ConfigOverrides } from '../clientConfig.js';

import type ExperimentIdPutParams from './experimentIdPut.parameters.js';

import { type ResponseDEFAULT_ERROR } from '../responses/DEFAULT_ERROR.js';
import { type ResponseUNPROCESSABLE_ENTITY } from '../responses/UNPROCESSABLE_ENTITY.js';
import type ExperimentIdPutResponse from './experimentIdPut.responses.js';
import {
  type Response200,
  type Response401,
  type Response403,
  type Response404,
  type Response409,
} from './experimentIdPut.responses.js';

/**
 * Update a experiment record with the given JSON data.
 *
 * autogenerated
 *
 * @async
 **/
const experimentIdPut = async (
  parameters: ExperimentIdPutParams & { config?: ConfigOverrides },
): Promise<ExperimentIdPutResponse> => {
  const {
    body,
    params: { experiment_id },
    config,
  } = parameters;
  const url = `${config?.basePath ?? ''}/experiment/${encodeURIComponent(experiment_id.toString())}`;
  const localFetch = config?.fetch ?? fetch;
  const headers = new Headers(config?.defaultParams?.headers);

  if (config?.auth?.bearer != null) {
    headers.set('authorization', `Bearer ${config.auth.bearer}`);
  }
  headers.set('Content-Type', 'application/json');

  const method = 'PUT';
  const requestMeta = {
    url,
    method,
    parameters,
  };

  const response = await localFetch(url, {
    ...config?.defaultParams,
    method,
    headers,
    body: JSON.stringify(body),
  });

  switch (response.status) {
    case 200:
      return {
        status: 200,
        data: (await response.json()) as Response200,
        response,
        request: requestMeta,
      };
    case 401:
      return {
        status: 401,
        data: (await response.json()) as Response401,
        response,
        request: requestMeta,
      };
    case 403:
      return {
        status: 403,
        data: (await response.json()) as Response403,
        response,
        request: requestMeta,
      };
    case 404:
      return {
        status: 404,
        data: (await response.json()) as Response404,
        response,
        request: requestMeta,
      };
    case 409:
      return {
        status: 409,
        data: (await response.json()) as Response409,
        response,
        request: requestMeta,
      };
    case 422:
      return {
        status: 422,
        data: (await response.json()) as ResponseUNPROCESSABLE_ENTITY,
        response,
        request: requestMeta,
      };
    default:
      if (response.status !== 0) {
        return {
          status: 'default',
          data: (await response.json()) as ResponseDEFAULT_ERROR,
          response,
          request: requestMeta,
        };
      }
      return {
        status: -1,
        response,
        request: requestMeta,
      };
  }
};

export default experimentIdPut;
