import { type ConfigOverrides } from '../clientConfig.js';

import type ExperimentPostParams from './experimentPost.parameters.js';

import { type ResponseDEFAULT_ERROR } from '../responses/DEFAULT_ERROR.js';
import { type ResponseUNPROCESSABLE_ENTITY } from '../responses/UNPROCESSABLE_ENTITY.js';
import type ExperimentPostResponse from './experimentPost.responses.js';
import {
  type Response201,
  type Response401,
  type Response403,
  type Response409,
} from './experimentPost.responses.js';

/**
 * Create a new experiment record in the database.
 *
 * autogenerated
 *
 * @async
 **/
const experimentPost = async (
  parameters: ExperimentPostParams & { config?: ConfigOverrides },
): Promise<ExperimentPostResponse> => {
  const { body, config } = parameters;
  const url = `${config?.basePath ?? ''}/experiment`;
  const localFetch = config?.fetch ?? fetch;
  const headers = new Headers(config?.defaultParams?.headers);

  if (config?.auth?.bearer != null) {
    headers.set('authorization', `Bearer ${config.auth.bearer}`);
  }
  headers.set('Content-Type', 'application/json');

  const method = 'POST';
  const requestMeta = {
    url,
    method,
    parameters,
  };

  const response = await localFetch(url, {
    ...config?.defaultParams,
    method,
    headers,
    body: JSON.stringify(body),
  });

  switch (response.status) {
    case 201:
      return {
        status: 201,
        data: (await response.json()) as Response201,
        response,
        request: requestMeta,
      };
    case 401:
      return {
        status: 401,
        data: (await response.json()) as Response401,
        response,
        request: requestMeta,
      };
    case 403:
      return {
        status: 403,
        data: (await response.json()) as Response403,
        response,
        request: requestMeta,
      };
    case 409:
      return {
        status: 409,
        data: (await response.json()) as Response409,
        response,
        request: requestMeta,
      };
    case 422:
      return {
        status: 422,
        data: (await response.json()) as ResponseUNPROCESSABLE_ENTITY,
        response,
        request: requestMeta,
      };
    default:
      if (response.status !== 0) {
        return {
          status: 'default',
          data: (await response.json()) as ResponseDEFAULT_ERROR,
          response,
          request: requestMeta,
        };
      }
      return {
        status: -1,
        response,
        request: requestMeta,
      };
  }
};

export default experimentPost;
