import { type ConfigOverrides } from '../clientConfig.js';

import type ExperimentIdDriftSearchPostParams from './experimentIdDriftSearchPost.parameters.js';

import { type ResponseDEFAULT_ERROR } from '../responses/DEFAULT_ERROR.js';
import { type ResponseUNPROCESSABLE_ENTITY } from '../responses/UNPROCESSABLE_ENTITY.js';
import type ExperimentIdDriftSearchPostResponse from './experimentIdDriftSearchPost.responses.js';
import {
  type Response200,
  type Response403,
  type Response404,
} from './experimentIdDriftSearchPost.responses.js';

/**
 * Get a paginated list of drift Jobs based on the provided JSON query
and MongoDB format.
 * 
 * autogenerated
 * 
 * @async
 **/
const experimentIdDriftSearchPost = async (
  parameters: ExperimentIdDriftSearchPostParams & { config?: ConfigOverrides },
): Promise<ExperimentIdDriftSearchPostResponse> => {
  const {
    body,
    params: { page, page_size, experiment_id },
    config,
  } = parameters;
  const url = `${config?.basePath ?? ''}/experiment/${encodeURIComponent(experiment_id.toString())}/drift/search`;
  const localFetch = config?.fetch ?? fetch;
  const headers = new Headers(config?.defaultParams?.headers);

  if (config?.auth?.bearer != null) {
    headers.set('authorization', `Bearer ${config.auth.bearer}`);
  }
  headers.set('Content-Type', 'application/json');

  const method = 'POST';
  const requestMeta = {
    url,
    method,
    parameters,
  };

  const response = await localFetch(
    `${url}?${new URLSearchParams({ ...(page != null && { ['page']: page.toString() }), ...(page_size != null && { ['page_size']: page_size.toString() }) }).toString()}`,
    {
      ...config?.defaultParams,
      method,
      headers,
      body: JSON.stringify(body),
    },
  );

  switch (response.status) {
    case 200:
      return {
        status: 200,
        data: (await response.json()) as Response200,
        response,
        request: requestMeta,
      };
    case 403:
      return {
        status: 403,
        data: (await response.json()) as Response403,
        response,
        request: requestMeta,
      };
    case 404:
      return {
        status: 404,
        data: (await response.json()) as Response404,
        response,
        request: requestMeta,
      };
    case 422:
      return {
        status: 422,
        data: (await response.json()) as ResponseUNPROCESSABLE_ENTITY,
        response,
        request: requestMeta,
      };
    default:
      if (response.status !== 0) {
        return {
          status: 'default',
          data: (await response.json()) as ResponseDEFAULT_ERROR,
          response,
          request: requestMeta,
        };
      }
      return {
        status: -1,
        response,
        request: requestMeta,
      };
  }
};

export default experimentIdDriftSearchPost;
