import { type ConfigOverrides } from '../clientConfig.js';

import type ExperimentIdGetParams from './experimentIdGet.parameters.js';

import { type ResponseDEFAULT_ERROR } from '../responses/DEFAULT_ERROR.js';
import type ExperimentIdGetResponse from './experimentIdGet.responses.js';
import { type Response200, type Response404 } from './experimentIdGet.responses.js';

/**
 * Retrieve an experiment by its ID from the database.
 *
 * autogenerated
 *
 * @async
 **/
const experimentIdGet = async (
  parameters: ExperimentIdGetParams & { config?: ConfigOverrides },
): Promise<ExperimentIdGetResponse> => {
  const {
    params: { experiment_id },
    config,
  } = parameters;
  const url = `${config?.basePath ?? ''}/experiment/${encodeURIComponent(experiment_id.toString())}`;
  const localFetch = config?.fetch ?? fetch;
  const headers = new Headers(config?.defaultParams?.headers);

  if (config?.auth?.bearer != null) {
    headers.set('authorization', `Bearer ${config.auth.bearer}`);
  }

  const method = 'GET';
  const requestMeta = {
    url,
    method,
    parameters,
  };

  const response = await localFetch(url, {
    ...config?.defaultParams,
    method,
    headers,
  });

  switch (response.status) {
    case 200:
      return {
        status: 200,
        data: (await response.json()) as Response200,
        response,
        request: requestMeta,
      };
    case 404:
      return {
        status: 404,
        data: (await response.json()) as Response404,
        response,
        request: requestMeta,
      };
    default:
      if (response.status !== 0) {
        return {
          status: 'default',
          data: (await response.json()) as ResponseDEFAULT_ERROR,
          response,
          request: requestMeta,
        };
      }
      return {
        status: -1,
        response,
        request: requestMeta,
      };
  }
};

export default experimentIdGet;
