import { type ConfigOverrides } from '../clientConfig.js';

import type ExperimentIdDriftPostParams from './experimentIdDriftPost.parameters.js';

import { type ResponseDEFAULT_ERROR } from '../responses/DEFAULT_ERROR.js';
import { type ResponseUNPROCESSABLE_ENTITY } from '../responses/UNPROCESSABLE_ENTITY.js';
import type ExperimentIdDriftPostResponse from './experimentIdDriftPost.responses.js';
import {
  type Response201,
  type Response401,
  type Response403,
  type Response404,
} from './experimentIdDriftPost.responses.js';

/**
 * Create a new drift Job record in the database.
 *
 * autogenerated
 *
 * @async
 **/
const experimentIdDriftPost = async (
  parameters: ExperimentIdDriftPostParams & { config?: ConfigOverrides },
): Promise<ExperimentIdDriftPostResponse> => {
  const {
    body,
    params: { experiment_id },
    config,
  } = parameters;
  const url = `${config?.basePath ?? ''}/experiment/${encodeURIComponent(experiment_id.toString())}/drift`;
  const localFetch = config?.fetch ?? fetch;
  const headers = new Headers(config?.defaultParams?.headers);

  if (config?.auth?.bearer != null) {
    headers.set('authorization', `Bearer ${config.auth.bearer}`);
  }
  headers.set('Content-Type', 'application/json');

  const method = 'POST';
  const requestMeta = {
    url,
    method,
    parameters,
  };

  const response = await localFetch(url, {
    ...config?.defaultParams,
    method,
    headers,
    body: JSON.stringify(body),
  });

  switch (response.status) {
    case 201:
      return {
        status: 201,
        data: (await response.json()) as Response201,
        response,
        request: requestMeta,
      };
    case 401:
      return {
        status: 401,
        data: (await response.json()) as Response401,
        response,
        request: requestMeta,
      };
    case 403:
      return {
        status: 403,
        data: (await response.json()) as Response403,
        response,
        request: requestMeta,
      };
    case 404:
      return {
        status: 404,
        data: (await response.json()) as Response404,
        response,
        request: requestMeta,
      };
    case 422:
      return {
        status: 422,
        data: (await response.json()) as ResponseUNPROCESSABLE_ENTITY,
        response,
        request: requestMeta,
      };
    default:
      if (response.status !== 0) {
        return {
          status: 'default',
          data: (await response.json()) as ResponseDEFAULT_ERROR,
          response,
          request: requestMeta,
        };
      }
      return {
        status: -1,
        response,
        request: requestMeta,
      };
  }
};

export default experimentIdDriftPost;
