import { type ConfigOverrides } from '../clientConfig.js';

import type UserSearchPostParams from './userSearchPost.parameters.js';

import { type ResponseDEFAULTERROR } from '../responses/DEFAULT_ERROR.js';
import { type ResponseUNPROCESSABLEENTITY } from '../responses/UNPROCESSABLE_ENTITY.js';
import type UserSearchPostResponse from './userSearchPost.responses.js';
import {
  type Response200,
  type Response401,
  type Response403,
} from './userSearchPost.responses.js';

/**
 * Retrieve a paginated list of users based on the provided JSON query
and MongoDB format.
 * 
 * autogenerated
 * 
 * @async
 **/
const userSearchPost = async (
  parameters: UserSearchPostParams & { config?: ConfigOverrides },
): Promise<UserSearchPostResponse> => {
  const { body, params: { page, page_size } = {}, config } = parameters;
  const url = `${config?.basePath ?? ''}/user/search`;
  const localFetch = config?.fetch ?? fetch;
  const headers = new Headers(config?.defaultParams?.headers);

  if (config?.auth?.bearer != null) {
    headers.set('authorization', `Bearer ${config.auth.bearer}`);
  }
  headers.set('Content-Type', 'application/json');

  const method = 'POST';
  const requestMeta = {
    url,
    method,
    parameters,
  };

  const response = await localFetch(
    `${url}?${new URLSearchParams({ ...(page != null && { ['page']: page.toString() }), ...(page_size != null && { ['page_size']: page_size.toString() }) }).toString()}`,
    {
      ...config?.defaultParams,
      method,
      headers,
      body: JSON.stringify(body),
    },
  );

  switch (response.status) {
    case 200:
      return {
        status: 200,
        data: (await response.json()) as Response200,
        response,
        request: requestMeta,
      };
    case 401:
      return {
        status: 401,
        data: (await response.json()) as Response401,
        response,
        request: requestMeta,
      };
    case 403:
      return {
        status: 403,
        data: (await response.json()) as Response403,
        response,
        request: requestMeta,
      };
    case 422:
      return {
        status: 422,
        data: (await response.json()) as ResponseUNPROCESSABLEENTITY,
        response,
        request: requestMeta,
      };
    default:
      if (response.status !== 0) {
        return {
          status: 'default',
          data: (await response.json()) as ResponseDEFAULTERROR,
          response,
          request: requestMeta,
        };
      }
      return {
        status: -1,
        response,
        request: requestMeta,
      };
  }
};

export default userSearchPost;
