import { type ApiFunction } from '../apiFunction.js';

import { type ResponseDEFAULT_ERROR } from '../responses/DEFAULT_ERROR.js';
import type UserPostResponse from './userPost.responses.js';
import {
  type Response201,
  type Response401,
  type Response403,
  type Response409,
} from './userPost.responses.js';

/**
 * Register and create the token owner as new user.
 *
 * autogenerated
 *
 * @async
 **/
const userPost: ApiFunction<undefined, UserPostResponse> = async (parameters = {}) => {
  const { config } = parameters;
  const url = `${config?.basePath ?? ''}/user`;
  const localFetch = config?.fetch ?? fetch;
  const headers = new Headers(config?.defaultParams?.headers);

  if (config?.auth?.bearer != null) {
    headers.set('authorization', `Bearer ${config.auth.bearer}`);
  }

  const method = 'POST';
  const requestMeta = {
    url,
    method,
  };

  const response = await localFetch(url, {
    ...config?.defaultParams,
    method,
    headers,
  });

  switch (response.status) {
    case 201:
      return {
        status: 201,
        data: (await response.json()) as Response201,
        response,
        request: requestMeta,
      };
    case 401:
      return {
        status: 401,
        data: (await response.json()) as Response401,
        response,
        request: requestMeta,
      };
    case 403:
      return {
        status: 403,
        data: (await response.json()) as Response403,
        response,
        request: requestMeta,
      };
    case 409:
      return {
        status: 409,
        data: (await response.json()) as Response409,
        response,
        request: requestMeta,
      };
    default:
      if (response.status !== 0) {
        return {
          status: 'default',
          data: (await response.json()) as ResponseDEFAULT_ERROR,
          response,
          request: requestMeta,
        };
      }
      return {
        status: -1,
        response,
        request: requestMeta,
      };
  }
};

export default userPost;
