/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ExperimentExperimentIdIndexImport } from './routes/experiment.$experimentId/index'
import { Route as ExperimentExperimentIdDriftDriftIdImport } from './routes/experiment.$experimentId/drift.$driftId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExperimentExperimentIdIndexRoute =
  ExperimentExperimentIdIndexImport.update({
    id: '/experiment/$experimentId/',
    path: '/experiment/$experimentId/',
    getParentRoute: () => rootRoute,
  } as any)

const ExperimentExperimentIdDriftDriftIdRoute =
  ExperimentExperimentIdDriftDriftIdImport.update({
    id: '/experiment/$experimentId/drift/$driftId',
    path: '/experiment/$experimentId/drift/$driftId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/experiment/$experimentId/': {
      id: '/experiment/$experimentId/'
      path: '/experiment/$experimentId'
      fullPath: '/experiment/$experimentId'
      preLoaderRoute: typeof ExperimentExperimentIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/experiment/$experimentId/drift/$driftId': {
      id: '/experiment/$experimentId/drift/$driftId'
      path: '/experiment/$experimentId/drift/$driftId'
      fullPath: '/experiment/$experimentId/drift/$driftId'
      preLoaderRoute: typeof ExperimentExperimentIdDriftDriftIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiment/$experimentId': typeof ExperimentExperimentIdIndexRoute
  '/experiment/$experimentId/drift/$driftId': typeof ExperimentExperimentIdDriftDriftIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiment/$experimentId': typeof ExperimentExperimentIdIndexRoute
  '/experiment/$experimentId/drift/$driftId': typeof ExperimentExperimentIdDriftDriftIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiment/$experimentId/': typeof ExperimentExperimentIdIndexRoute
  '/experiment/$experimentId/drift/$driftId': typeof ExperimentExperimentIdDriftDriftIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/experiment/$experimentId'
    | '/experiment/$experimentId/drift/$driftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/experiment/$experimentId'
    | '/experiment/$experimentId/drift/$driftId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/experiment/$experimentId/'
    | '/experiment/$experimentId/drift/$driftId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExperimentExperimentIdIndexRoute: typeof ExperimentExperimentIdIndexRoute
  ExperimentExperimentIdDriftDriftIdRoute: typeof ExperimentExperimentIdDriftDriftIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExperimentExperimentIdIndexRoute: ExperimentExperimentIdIndexRoute,
  ExperimentExperimentIdDriftDriftIdRoute:
    ExperimentExperimentIdDriftDriftIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/experiment/$experimentId/",
        "/experiment/$experimentId/drift/$driftId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/experiment/$experimentId/": {
      "filePath": "experiment.$experimentId/index.tsx"
    },
    "/experiment/$experimentId/drift/$driftId": {
      "filePath": "experiment.$experimentId/drift.$driftId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
